baseURL = 'https://jodin.org/'
languageCode = 'en-us'
title = 'Jodin'
theme = ['hugo-video', 'ardeidae']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  github = 'https://github.com/nik1oo/jodin'
